package com.saei.domain.commons;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sat Oct 18 10:30:51 BRT 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class JurosParcelamento
    extends com.saei.domain.commons.BaseJurosParcelamento
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1413639051056L;

}
