package com.saei.domain.commons;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Wed Oct 08 22:49:52 BRT 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Negocio
    extends com.saei.domain.commons.BaseNegocio
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1412819392013L;

}
