package com.saei.domain.commons;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Aug 31 20:50:28 BRT 2014]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class PagamentoPeer
    extends com.saei.domain.commons.BasePagamentoPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1409529028307L;

}
