package com.enums;

public enum Regras {
	PERFIL_CRIAR, PERFIL_ALTERAR, PERFIL_EXCLUIR,
	ACERVO_CRIAR, ACERVO_ALTERAR, ACERVO_EXCLUIR, ACERVO_CONSULTAR,
	EMPRESTIMO_CRIAR, EMPRESTIMO_RENOVAR,
	DEVOLUCAO,
	RESERVA,
	RELATORIO,
	RECEBER_PAGAMENTO;
	
	

}