package com.saei.domain.commons;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Thu Aug 28 15:48:46 PDT 2014]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class ImportacaoArquivoProdutosLog
    extends com.saei.domain.commons.BaseImportacaoArquivoProdutosLog
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1409266126265L;

}
